schema_version = "1.0.0"

id = "batch_bone_constraints"
version = "1.1.2"
name = "Batch Bone Constraints"
tagline = "Batch bone constraints to the selected multiple armatures"
maintainer = "distinctive-mark"

type = "add-on"
tags = ["Rigging", "Animation"]
blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]

[build]
paths_exclude_pattern = [
  "__pycache__/",
  ".*",
  "*.zip",
  "*.png",
  "*.md",
  "LICENSE",
]